project: pop2piano
dataset:
  target_length: 256
  input_length: 1024
  n_bars: 2
  sample_rate: 22050
t5:
  feed_forward_proj: gated-gelu
  tie_word_embeddings: false
  tie_encoder_decoder: false
  vocab_size: 2400
  n_positions: 1024
  relative_attention_num_buckets: 32
tokenizer:
  vocab_size:
    special: 4
    note: 128
    velocity: 2
    time: 100
trainer:
  max_epochs: 5000
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 20
  gradient_clip_val: 3.0
dataloader:
  batch_size: 32
  num_workers: 4
inference:
  batch_size: 64
